VERSION = "20260811"
//------------------------------------------------------------------------------
//- ↓ 設定 ここから -----------------------------------------------------------

//-------------------
// 1.インストール先
//-------------------
// 1.1.フォルダ名
//   非推奨：日本語表記
_InstallDir = "setup-sample"

//-------------------
// 2.ショートカット
//-------------------
// 2.1.表示名
_Shortcut = "セットアップ・サンプル"

// 2.2.["ショートカット名", "実行ファイル", "アイコン"]
//   必須：二次配列 [] 最後に "," を付与すること
_ShortcutItem = [
	["01 notepad.exe", "c:\windows\system32\notepad.exe", "c:\windows\system32\SHELL32.dll, 24"],
	["02 sample.txt", "sample.txt", "sample.ico"],
	["03 sample.txt", "sample.txt"],
]

// 2.3.アンインストール・ショートカット名
_ShortcutUninstall = "99 Uninstall"

//- ↑ 設定 ここまで -----------------------------------------------------------
//------------------------------------------------------------------------------

// 初期設定
//   実ファイルの格納先を %LOCALAPPDATA% に設定しています。
//   "C:\Program Files\" などを要求するなら、別のセキュリティ対応インストーラーを使用することをお勧めします。
InstDir      = env.LOCALAPPDATA + "\" + _InstallDir
ShortcutDir  = env.APPDATA + "\Microsoft\Windows\Start Menu\Programs\" + _Shortcut
SetupFileDir = ".\setup-files"

// 共通変数
CR   = char(13)
LF   = char(10)
CRLF = CR + LF
TAB  = char(9)

ESC = char(27) + "["

// 関数
DOS = function(cmd = "")
	// 末尾プロンプトを非表示
	rtn = exec("@echo off && " + cmd)
		a1 = []
		for s1 in rtn.output.split(LF)
			// LF, CRを別々に消去
			s1 = s1.replace(LF, "").replace(CR, "")
			// 追加（空白行含む）
			a1.push(s1)
		end for
		// 配列を返す
		rtn.output = a1
	return rtn
end function

PS5 = function(cmd = "")
	return DOS("powershell.exe -Command """ + cmd + """")
end function

E1 = function(esc = "0m", text = "")
	if text then
		text = text + ESC + "0m"
	end if
	print (ESC + esc + text), ""
end function

E2 = function(esc = "0m", text = "")
	E1(esc, text)
	print
end function

CLS = function()
	// Windows
	PS5("Clear-Host")
end function

P1 = function(text = "")
	print text, ""
end function

P2 = function(text = "")
	print text
end function

NOW = function(format = "yyyy-MM-dd HH:mm:ss")
	return _dateStr(_dateVal, format)
end function

//-------------
// 前処理開始
//-------------
CLS

E2("97;44m", " " + _Shortcut + " ")
P2

// ファイル存在チェック
errorCnt = 0
for i1 in _ShortcutItem.indexes
	if _ShortcutItem[i1].len < 2 then
		E1("91m", "NG ")
		P1(_ShortcutItem[i1][0] + " ")
		E2("95m", "No file name!")
		errorCnt = errorCnt + 1
	else
		if not file.exists(_ShortcutItem[i1][1]) then
			fn = SetupFileDir + "\" + _ShortcutItem[i1][1]
			if not file.exists(fn) then
				E1("91m", "NG ")
				P1(_ShortcutItem[i1][0] + " ")
				E2("95m", _ShortcutItem[i1][1] + "?")
				errorCnt = errorCnt + 1
			end if
		end if
	end if
end for

// 中止
if errorCnt > 0 then
	P2
	E1("95m", "2.2._ShortcutItem")
	E2("37m", " を見直してください")
	exit
end if

// 続行
E2("93m", "1.インストール・フォルダ")
P1("    ")
E2("37m", InstDir)
P2
E2("93m", "2.1.ショートカット・フォルダ")
P1("    ")
E2("37m", ShortcutDir)
P2
E2("93m", "2.2.ショートカット・アイテム")
P1("    ")
E1("95m", "*ショートカット名")
P1(TAB)
E1("96m", "*実行ファイル")
P1(TAB)
E1("92m", "*アイコン")

for i1 in _ShortcutItem.indexes
	P2
	P1("    ")
	E1("95m", _ShortcutItem[i1][0])
	P1(TAB)
	E1("96m", _ShortcutItem[i1][1])
	if _ShortcutItem[i1].len > 2 then
		P1(TAB)
		E1("92m", _ShortcutItem[i1][2])
	end if
end for

P2
P1("    ")
E2("95m", _ShortcutUninstall)

// 注意
if file.exists(InstDir) and file.info(InstDir).isDirectory then
	P2
	E2("91m", "注意：")
	E2("96m", "    " + InstDir)
	P2 "    が既に存在します。"
	P2 "    必要に応じて、バックアップしてください。"
	E2("91m", "    同名ファイルは上書きされます。")
end if

//-------------------
// インストール開始
//-------------------
P2
E1("93m", "インストールしますか? [Y/n] ")
	inputStr = input
	P2
	if inputStr != "y" and inputStr != "Y" then
		P2 "中止します..."
		exit
	end if

P2 "インストール中..."

// インストールフォルダへコピー
file.makedir InstDir

src  = SetupFileDir + "\*"
dest = InstDir

PS5("Copy-Item -Path '" + src + "' -Destination '" + dest + "' -Recurse -Force")

//---------------------
// ショートカット作成
//---------------------
file.makedir ShortcutDir

for i1 in _ShortcutItem.indexes
	shortcutPath = ShortcutDir + "\" + _ShortcutItem[i1][0] + ".lnk"

	targetPath = _ShortcutItem[i1][1]
		if not file.exists(targetPath) then
			targetPath = InstDir + "\" + targetPath
		end if

	iconPath = ""
		if _ShortcutItem[i1].len > 2 and _ShortcutItem[i1][2] != "" then
			fn = _ShortcutItem[i1][2].split(",")[0]
			if file.exists(fn) then
				iconPath = _ShortcutItem[i1][2]
			else
				iconPath = InstDir + "\" + _ShortcutItem[i1][2]
			end if
		end if

	ps1 = "" +
		"$s = New-Object -ComObject WScript.Shell; " +
		"$lnk = $s.CreateShortcut('" + shortcutPath + "'); " +
		"$lnk.TargetPath = '" + targetPath + "'; " +
		"$lnk.IconLocation = '" + iconPath + "'; " +
		"$lnk.Save()"

	PS5(ps1)
end for

//-------------------------------
// アンインストールファイル作成
//-------------------------------
// unistall-xxx_yyyyMMdd.bat
UnistallFn01 = "unistall-" + _InstallDir + "_" + NOW("yyyyMMdd") + ".bat"
	UninstallBatch01 = [
		"@echo off",
		"echo [" + _Shortcut + "]",
		"echo.",
		"echo - " + InstDir,
		"echo - " + ShortcutDir,
		"echo.",
		"set /p input=""アンインストールしますか? [Y/n] """,
		"if /i not ""%input%"" == ""Y"" (",
		"  echo.",
		"  echo 中止します...",
		"  sleep 2",
		"  exit /b",
		")",
		"echo.",
		"echo アンインストール開始...",
		"rmdir /S /Q """ + InstDir + """",
		"rmdir /S /Q """ + ShortcutDir + """",
		"sleep 2",
		"echo 終了",
		"sleep 2",
		"del ""%~f0%""",
	]

	file.writeLines(UnistallFn01, UninstallBatch01)

	PS5("Move-Item -Path '" + UnistallFn01 + "' '" + InstDir + "' -Force")

// unistall-xxx.bat
UnistallFn00 = "unistall-" + _InstallDir + ".bat"
	UninstallBatch00 = [
		"@echo off",
		"copy """ + InstDir + "\" + UnistallFn01 + """ ""%TEMP%""",
		"cd ""%TEMP%""",
		"cls",
		UnistallFn01,
	]

	file.writeLines(UnistallFn00, UninstallBatch00)

	PS5("Move-Item -Path '" + UnistallFn00 + "' '" + InstDir + "' -Force")

	shortcutPath = ShortcutDir + "\" + _ShortcutUninstall + ".lnk"
	targetPath = InstDir + "\" + UnistallFn00

	ps1 = "" +
		"$s = New-Object -ComObject WScript.Shell; " +
		"$lnk = $s.CreateShortcut('" + shortcutPath + "'); " +
		"$lnk.TargetPath = '" + targetPath + "'; " +
		"$lnk.Save()"

	PS5(ps1)

//-------
// 終了
//-------
P2 "インストール完了"
